apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  generation: 2
  labels:
    app: todo-web-app-h2
  name: todo-web-app-h2
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: todo-web-app-h2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: todo-web-app-h2
    spec:
      containers:
      - image: cjragas/todo-web-app-h2:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: todo-web-app-h2
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-web-app-h2
  name: todo-web-app-h2
  namespace: default
spec:
  ports:
  - nodePort: 30510
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: todo-web-app-h2
  sessionAffinity: ClientIP
  type: LoadBalancer