apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: currency-exchange
  name: currency-exchange
  namespace: default
spec:
  replicas: 0
  minReadySeconds: 45
  selector:
    matchLabels:
      app: currency-exchange
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: currency-exchange
    spec:
      containers:
      - image: cjragas/currency-exchange:2.0.0-RELEASE
        imagePullPolicy: IfNotPresent
        name: currency-exchange
        env:
        - name: SPRING_CLOUD_GCP_TRACE_ENABLED
          value: "true"
        ports:
        - name: liveness-port
          containerPort: 8000
        readinessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 60
        livenessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 60
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: currency-exchange
  name: currency-exchange
  namespace: default
spec:
  ports:
  - port: 8000 
    protocol: TCP
    targetPort: 8000 
  selector:
    app: currency-exchange
  sessionAffinity: None
  type: LoadBalancer