apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  generation: 2
  labels:
    app: hw-rest-api
  name: hw-rest-api
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hw-rest-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hw-rest-api
    spec:
      containers:
      - image: cjragas/hw-rest-api:0.0.1
        imagePullPolicy: IfNotPresent
        name: hw-rest-api
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hw-rest-api
  name: hw-rest-api
  namespace: default
spec:
  ports:
  - nodePort: 30510
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hw-rest-api
  sessionAffinity: None
  type: LoadBalancer